SUPPORTED_MODELS = [
    "Anima",
    "Boogu",
    "Chroma",
    "Ernie",
    "Flux 1.0",
    "Flux.1 D",
    "Flux.1 Kontext",
    "Flux.1 Krea",
    "Flux.1 S",
    "Flux.2 D",
    "Flux.2 Klein 4B",
    "Flux.2 Klein 4B-base",
    "Flux.2 Klein 9B",
    "Flux.2 Klein 9B-base",
    "HiDream",
    "HiDream-O1",
    "Ideogram 4.0",
    "Illustrious",
    "Illustrious 0.1",
    "Krea 2",
    "Krea2",
    "LTXV",
    "LTXV 2.3",
    "LTXV2",
    "Lumina",
    "NoobAI",
    "Other",
    "Pony",
    "Pony V7",
    "Qwen",
    "SD 1.4",
    "SD 1.5",
    "SD 1.5 Hyper",
    "SD 1.5 LCM",
    "SDXL 0.9",
    "SDXL 1.0",
    "SDXL 1.0 LCM",
    "SDXL Distilled",
    "SDXL Hyper",
    "SDXL Lightning",
    "Upscaler",
    "Wan Video",
    "Wan Video 1.3B t2v",
    "Wan Video 14B i2v 480p",
    "Wan Video 14B i2v 720p",
    "Wan Video 14B t2v",
    "Wan Video 2.2 I2V-A14B",
    "Wan Video 2.2 T2V-A14B",
    "Wan Video 2.2 TI2V-5B",
    "Z-Image",
    "ZImageBase",
    "ZImageTurbo"
]
